name: Deploy to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 212.227.28.148 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no root@212.227.28.148 "
            cd /root/BST &&
            git pull &&
            npm install &&
            npm run build &&
            npm install -g pm2 &&
            mkdir -p logs &&
            pm2 delete bst-app || true &&
            pm2 start ecosystem.config.js &&
            pm2 save &&
            pm2 startup
          "